#==========================================================================
# Description: Build Armbian
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#==========================================================================

name: Build armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS Release."
        required: false
        default: "bullseye"
        type: choice
        options:
          - jammy
          - bullseye
      armbian_board:
        description: "Select device board."
        required: false
        default: "all"
        type: choice
        options:
          - all
          - s922x_s905x3_s905d_s912_s905l3a
          - r66s_r68s_h66k_h68k_e25
          - eaidk-610_king3399_tn3399_kylin3399
          - vplus_tqc-a01_tanix-tx6
          - a311d
          - s922x
          - s922x-reva
          - s922x-ct2000
          - s905x3
          - s905x3-b
          - s905x2
          - s912
          - s912-m8s-pro
          - s905d
          - s905d-ki-pro
          - s905x
          - s905w
          - s905
          - s905l2
          - s905l3
          - s905l3a
          - s905l3b
          - s905lb-r3300l
          - rock5b
          - h88k
          - r66s
          - r68s
          - h66k
          - h68k
          - e25
          - eaidk-610
          - king3399
          - kylin3399
          - tn3399
          - beikeyun
          - l1pro
          - vplus
          - tqc-a01
          - tanix-tx6
          - lx-r3s
      armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "5.15.85_6.1.1"
        type: string
#        type: choice
#        options:
#          - 5.4.225_5.10.160_5.15.85
#          - 5.4.225_5.10.160
#          - 5.10.160_5.15.85
#          - 5.15.85_6.1.1
#          - 5.4.225
#          - 5.10.160
#          - 5.15.85
#          - 6.1.1
      auto_kernel:
        description: "Auto use the latest kernel."
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository."
        required: false
        default: "https://github.com/ophub/kernel/tree/main/pub"
      armbian_size:
        description: "Set armbian rootfs size(Unit: MiB)."
        required: false
        default: "2560"
      armbian_fstype:
        description: "Select armbian rootfs type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_sign:
        description: "Set armbian custom name."
        required: false
        default: ""

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download source code
        id: down
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          df -hT ${PWD}
          git clone -q --single-branch --depth 1 -b master https://github.com/TKaxv-7S/armbian-build.git build
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Rebuild Armbian
        uses: TKaxv-7S/tk-armbian@main_test
        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
        with:
          build_target: armbian
          armbian_path: build/output/images/*.img.gz
          armbian_board: ${{ inputs.armbian_board }}
          armbian_kernel: ${{ inputs.armbian_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          armbian_size: ${{ inputs.armbian_size }}
          armbian_fstype: ${{ inputs.armbian_fstype }}
          armbian_sign: ${{ inputs.armbian_sign }}
          gh_token: ${{ secrets.GH_TOKEN }}

